In [1]:
import numpy as np

## Data Types & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create DataFrame from a Numpy Array

In [13]:
import pandas as pd

In [14]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating Arrays

In [15]:
sample_array = np.array([1,2,3])

In [16]:
sample_array

array([1, 2, 3])

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[2, 0, 3, 0, 8],
       [0, 7, 7, 1, 2],
       [6, 1, 6, 8, 4]])

In [22]:
random_array.size, random_array.shape

(15, (3, 5))

In [24]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.50680324, 0.91802596, 0.20804855],
       [0.45581633, 0.18327383, 0.82163733],
       [0.24270925, 0.81151015, 0.36188977],
       [0.78561195, 0.80791198, 0.38886672],
       [0.93367492, 0.65060349, 0.13610249]])

In [26]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.63907171, 0.99493798, 0.13528881],
       [0.4292086 , 0.03551371, 0.40294839],
       [0.27743886, 0.54685775, 0.8197501 ],
       [0.32019803, 0.14774701, 0.30870679],
       [0.60521943, 0.07549374, 0.60556732]])

In [28]:
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[8, 2, 3],
       [5, 8, 0],
       [9, 4, 7],
       [3, 1, 1],
       [1, 1, 0]])

In [30]:
#Pseudo -random numbers
np.random.seed(seed = 0)

# due to the above func the random no.s will not change

random_array5 = np.random.randint(10, size=(5,3))
random_array5

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [31]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

# 3. Viewing Arrays & Matrices

In [32]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [33]:
a1[0]

1

In [34]:
a2[0]

array([1. , 2. , 3.3])

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [39]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [40]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [44]:
# get the 1st 4 numbers of the inner most array
a4[:, :, :, :4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

In [45]:
a4[1][2][0][:]

array([2, 3, 4, 1, 2])

# 4. Manipulating & Comparing Arrays

### Arithmetic

In [46]:
a1

array([1, 2, 3])

In [48]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [49]:
a1 + ones

array([2., 3., 4.])

In [50]:
a1 - ones

array([0., 1., 2.])

In [52]:
a1, a2 ,a2 * a1

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[ 1. ,  4. ,  9.9],
        [ 4. , 10. , 19.5]]))

In [55]:
# a2 * a3 -> wont work broadcasting issue
# search numpy broadcasting

# how to reshape numpy array (to reshape a2 to be compatible with a3)

# Aggregation

### Aggregation -> performing same oprn on a no. of things

In [57]:
a1

array([1, 2, 3])

In [59]:
sum(a1), np.sum(a1)

(6, 6)

Use Python's methods (sum()) on python datatypes and use Numpy's methods on numpy arrays (np.sum()).

In [62]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [63]:
massive_array[:5]

array([0.59816399, 0.17370251, 0.49752936, 0.51231935, 0.41529741])

In [64]:
%timeit sum(massive_array)  #Python's sum()
%timeit np.sum(massive_array)  #Numpy's sum()

6.59 ms ± 142 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
41.5 µs ± 794 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [65]:
np.mean(a2)

3.6333333333333333

In [67]:
np.min(a2)

1.0

In [69]:
np.std(a2)

1.8226964152656422

In [70]:
np.var(a2)

3.3222222222222224

# Reshaping and Transposing

In [71]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [74]:
# a2 * a3
# Broadcasting Issue

In [75]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [79]:
# Checkout broadcasting rules

a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [80]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [81]:
# Transpose
a2, a2.T

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[1. , 4. ],
        [2. , 5. ],
        [3.3, 6.5]]))

In [83]:
a3, a3.T

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 array([[[ 1, 10],
         [ 4, 13],
         [ 7, 16]],
 
        [[ 2, 11],
         [ 5, 14],
         [ 8, 17]],
 
        [[ 3, 12],
         [ 6, 15],
         [ 9, 18]]]))

# Dot Product

In [84]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [85]:
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [86]:
# Element wise multiplication (Hadamard Product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [87]:
# Dot Product

# np.dot(mat1, mat2) # can multiply because matrix size 5x3 * 5x3
# so we tranpose the 2nd matrix

In [88]:
mat1, mat2.T

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 8, 9, 4, 3],
        [7, 1, 8, 3, 5],
        [7, 5, 9, 0, 0]]))

In [89]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [91]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [92]:
mat3.shape

(5, 5)

### Dot Product Example

In [100]:
np.random.seed(1)

# no of jars sold
jars_sold = np.random.randint(20, size=(5,3))
jars_sold

array([[ 5, 11, 12],
       [ 8,  9, 11],
       [ 5, 15,  0],
       [16,  1, 12],
       [ 7, 13,  6]])

In [101]:
import pandas as pd

# weekly_sales DataFrame
weekly_sales = pd.DataFrame(jars_sold,
                            index=['Mon', 'Tues', 'Wed', 'Thu', 'Fri'],
                            columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])

weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               5             11             12
Tues              8              9             11
Wed               5             15              0
Thu              16              1             12
Fri               7             13              6

In [102]:
# creating prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [105]:
# prices DataFrame

# remember to use reshape
jars_prices = pd.DataFrame(prices.reshape(1,3),
                            index=['Price'],
                            columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])

jars_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [106]:
weekly_sales.shape, jars_prices.shape

((5, 3), (1, 3))

In [113]:
np.dot(jars_prices, weekly_sales.T)

array([[282, 284, 170, 312, 246]])

In [111]:
weekly_totals = jars_prices.dot(weekly_sales.T)
weekly_totals

Mon  Tues  Wed  Thu  Fri
Price  282   284  170  312  246

In [115]:
# weekly_sales['Total ($)'] = weekly_totals
# doesn't work because of shapes

weekly_sales['Total ($)'] = weekly_totals.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               5             11             12        282
Tues              8              9             11        284
Wed               5             15              0        170
Thu              16              1             12        312
Fri               7             13              6        246

# Comparison Operators

In [117]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [118]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [120]:
# to store just boo_arr = and it will be dtype of bool array
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [121]:
a1 > 3

array([False, False, False])

In [122]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

# Sorting Arrays

In [124]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[9, 2, 4, 5, 2],
       [4, 2, 4, 7, 7],
       [9, 1, 7, 0, 6]])

In [125]:
np.sort(random_array)

array([[2, 2, 4, 5, 9],
       [2, 4, 4, 7, 7],
       [0, 1, 6, 7, 9]])

In [127]:
# to get the index in which we want to sort
random_array, np.argsort(random_array)

(array([[9, 2, 4, 5, 2],
        [4, 2, 4, 7, 7],
        [9, 1, 7, 0, 6]]),
 array([[1, 4, 2, 3, 0],
        [1, 0, 2, 3, 4],
        [3, 1, 4, 2, 0]], dtype=int64))

In [129]:
np.argmin(random_array), np.argmax(random_array)

(13, 0)

In [131]:
np.argmax(random_array, axis = 0)
#look at columnwise

array([0, 0, 2, 1, 1], dtype=int64)

In [132]:
np.argmax(random_array, axis = 1)
# row wise

array([0, 3, 0], dtype=int64)

# 6. Practical Example

<img src="6-step-ml-framework.png"/>

In [138]:
# turning an image into a numpy array
from matplotlib.image import imread

image_array = imread("6-step-ml-framework.png")
image_array[:3]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [139]:
image_array.size, image_array.shape, image_array.ndim

(17127936, (1296, 3304, 4), 3)